AllCops:
  TargetRubyVersion: 2.7.5

Layout/EndOfLine:
  EnforcedStyle: lf

Layout/HashAlignment:
  EnforcedColonStyle:
    - key
    - table

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/SoleNestedConditional:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false
